Practices/ViewComponentsExample/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewComponentsExample.Models
{
    public class Person
    {

        public string? PersonName { get; set; }
        public string? JobTitle { get; set; }
    }
}

Practices/ViewComponentsExample/Models/PersonGridModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewComponentsExample.Models
{
    public class PersonGridModel
    {
        public string GridTitle { get; set; } = string.Empty;
        public List<Person> Persons { get; set; } = new List<Person>();
    }
}

Practices/ViewComponentsExample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ViewComponentsExample.Models;

namespace ViewComponentsExample.Controllers
{
    [Route("[controller]")]
    public class HomeController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("/about")]
        public IActionResult About()
        {
            return View();
        }

        [Route("/friends-list")]
        public IActionResult LoadFriendsList()
        {
            PersonGridModel personGridModel = new PersonGridModel()
            {
                GridTitle = "Friends",
                Persons = new List<Person>(){
                new Person() { PersonName = "Khan", JobTitle = "Manager" },
                new Person() { PersonName = "Nehan", JobTitle = "Developer" },
                new Person() { PersonName = "Pathan", JobTitle = "ProductManager" },

                }
            };
            return ViewComponent("Grid", new{
                grid = personGridModel
            });
        }
        

       
    }
}

Practices/ViewComponentsExample/ViewComponents/GridViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ViewComponentsExample.Models;

namespace ViewComponentsExample.ViewComponents
{
    public class GridViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(PersonGridModel grid)
        {
            

            return View(grid); //invoked a partial view Views/Shared/Components/Grid/Default.cshtml 
        }
    }
}

Practices/ViewComponentsExample/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1>About</h1>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam, ea impedit iure, quo commodi ducimus ex asperiores deleniti tempore rerum sapiente incidunt doloremque, eveniet voluptatem! Sequi asperiores nisi assumenda magnam!
Maiores minima ut eveniet quae facere nesciunt assumenda illum, odit fugit hic modi, dolor ipsam. Voluptatem pariatur veniam minus nulla, tempora repudiandae, excepturi delectus dignissimos optio, officia quos maiores temporibus?
Similique necessitatibus nobis perspiciatis! Necessitatibus consequatur quas obcaecati expedita dignissimos nemo porro ullam, eum, consequuntur nulla vero esse, ratione ipsam autem perspiciatis minima aperiam numquam perferendis. Facere, illo. Est, quibusdam.
Dignissimos dolor dolorum quia blanditiis sequi, hic neque impedit ratione consequuntur voluptatibus? Blanditiis in voluptas quas repellat consectetur? Aspernatur deserunt numquam quia, excepturi doloribus harum aliquam magni molestiae assumenda modi.
Suscipit provident odio soluta eveniet. Optio tempore aut reiciendis soluta repudiandae pariatur dicta porro id natus, voluptatem eligendi nisi doloribus obcaecati suscipit iure error molestias. Maxime maiores similique incidunt beatae?
Officia temporibus obcaecati itaque ut ea optio. Repellendus magni ipsa aperiam voluptates sunt aspernatur suscipit expedita. Ducimus, eveniet? Tempore voluptates sit eos error earum officiis ratione cum impedit rem labore.
Ut culpa adipisci dignissimos id animi, necessitatibus vero? Dignissimos blanditiis corporis voluptatum eveniet, cumque nobis ut deserunt illo inventore eos consectetur ipsum facilis quisquam aliquam ipsa, vero cum incidunt. Eius?</p>

@{
    PersonGridModel personGridModel = new PersonGridModel()
            {
                GridTitle = "Employee List",
                Persons = new List<Person>(){
                new Person() { PersonName = "Dhruvii", JobTitle = "Manager" },
                new Person() { PersonName = "Aastha", JobTitle = "Developer" },
                new Person() { PersonName = "Hemanshi", JobTitle = "ProductManager" },

                }
            };

}

<vc:grid grid="personGridModel"></vc:grid>

Practices/ViewComponentsExample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<h1>Home</h1>
<button class="button button-blue-back" id="load-friends-button">Load Friends</button>
<div id="list"></div>
<script src="friends.js"></script>

Practices/ViewComponentsExample/Views/Shared/Components/Grid/Default.cshtml
@model PersonGridModel
<div class="box">
    <h3>@Model.GridTitle</h3>
    <table class="table w-100">
        <thead>
            <tr>
                <th>Sl. No</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var person in Model.Persons)
            {
                <tr>
                    <td>@person.PersonName</td>
                    <td>@person.JobTitle</td>
                </tr>

            }
        </tbody>

    </table>